name: selftrackingapp
description: Self tracking app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.17.2+39

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    get_it: ^4.0.0
    cached_network_image: ^2.0.0
    share: ^0.6.3+6
    firebase_messaging: ^6.0.13
    firebase_remote_config: ^0.3.0+3
    google_maps_flutter: ^0.5.21+3
    shared_preferences: ^0.5.6+3
    url_launcher: ^5.4.2
    http: ^0.12.0+4
    logger: ^0.8.3
    timeago: ^2.0.26
    google_fonts: ^0.3.9
    titled_navigation_bar: ^3.6.0
    date_format: ^1.0.8
    provider: ^4.0.4
    equatable: ^1.1.1
    geolocator: ^5.3.1
    async: ^2.4.0
    package_info: ^0.4.0+16
    connectivity: ^0.4.8+2
    dropdown_banner: ^1.4.0
    recursive_regex: ^0.1.3+2
    webview_flutter: ^0:3:19+9
    auto_size_text: ^2.1.0
    flutter_html: ^0.11.1
    flutter_colorpicker: ^0.3.4
    qr_code_scanner: ^0.0.12
    cloud_firestore: 0.13.5
   
  

    clustering_google_maps: ^0.1.2

    flutter_localizations:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/welcome_screen_bg.png
        - assets/images/bg.png
        - assets/lang/en.json
        - assets/lang/si.json
        - assets/lang/ta.json
        - assets/hospitals.json
        - assets/images/logo.png
        - assets/images/hospital_sign_map.png
        - assets/images/suspected_icon.png
        - assets/images/user_icon.png
        - assets/data/constant_data.json
        - assets/data/countries.json
        - assets/images/rehabilitation.svg
        - assets/images/suspect.svg
        - assets/images/locateme_24px.svg
        - assets/images/home_24px.svg
        - assets/images/death.svg
        - assets/images/contactus_24px.svg
        - assets/images/casefinder_24px.svg
        - assets/images/announcement_24px.svg
        - assets/images/ambulance.svg
        - assets/images/add_ic_call_24px.svg
        - assets/images/medical_consultion.png
        - assets/images/stay_safe.png
        
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
